// Generated by CoffeeScript 1.9.1
(function() {
  var K, N, computeWay, inputLines;

  inputLines = 0;

  N = K = 0;

  process.stdin.on('data', function(data) {
    var a, i, j, num, pr, ref;
    num = data.toString().split(" ");
    if (inputLines === 0) {
      inputLines++;
      N = Number(num[0]);
      return K = Number(num[1]);
    } else {
      a = [];
      for (i = j = 0, ref = N - 1; 0 <= ref ? j <= ref : j >= ref; i = 0 <= ref ? ++j : --j) {
        a.push(Number(num[i]));
      }
      pr = computeWay(N, K, a);
      console.log(pr);
      return process.exit(0);
    }
  });

  computeWay = function(N, K, a) {
    var factor, product, quo, rem;
    rem = (N - 1) % K;
    quo = parseInt((N - 1) / K);
    product = 1;
    factor = 0;
    product *= a[rem];
    while (factor < quo) {
      rem = rem + K;
      product *= a[rem];
      product %= 1000000007;
      factor++;
    }
    return product;
  };

}).call(this);
